### ISSUE TITLE
A standardized xml substance expressing system 

### ISSUE THREAD

**Issue by 3TUSK** [FrogCraft-Rebirth/ChemLab#2]
@Glease

**Comment by 3TUSK** [comment]
@wormzjl
Further discussion can put here.

**Comment by Glease** [comment]
wait a while, eclipse is down. no way to upload.

--- Original Message ---

**Comment by 3TUSK** [comment]
@Glease Dont rush... this is just a reminder for me...

**Comment by Glease** [comment]
Basically this is it. Glease/ChemLib@bd41444d55a714454bfb0131dc3afe6eeeb7392a
Because of the tremendous changes, I opened a new repo for it. Plz forgive me.

p.s.: that function evaluation has a long way to go. It may take me one week or more to complete it.

**Comment by 3TUSK** [comment]
Deprecated this repository for now...
