### ISSUE TITLE
Any necessary to support json?

### ISSUE THREAD

**Issue by 3TUSK** [FrogCraft-Rebirth/ChemLab#3]
Self-explained title.

**Comment by Glease** [comment]
Not really necessary. We only need to support one format. Xml or Json. We are not designing a **BIG** standard that would benifit a whole industry. We don't need to satisfy every single feature request from everyone.

Did I mentioned we coould just support json? Well, it's ok to mention it again.

**Comment by 3TUSK** [comment]
How about an external converter. Supporting TeX?

**Comment by Glease** [comment]
What the hell... IIRC, Tex is a language for printing. How you are supposed to use Tex to store data?

--- Original Message ---

**Comment by 3TUSK** [comment]
I mean, support TeX for presentation. NOT STORAGE

**Comment by Glease** [comment]
Well, my fault. In fact, we could just make it a plugin. The default implementation transform it into an Xml/Json document, while plugins make it a Tex document.

Actually, I'm thinking of turning this project (or my ChemLib) an open standard. We make reference implementation, and is open for other vendors.

--- Original Message ---

**Comment by 3TUSK** [comment]
Agree
